apiVersion: v1
kind: Service
metadata:
  name: angular-v10-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular-v10  